/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedRunsIndexRouteImport } from './routes/_authenticated/runs.index'
import { Route as AuthenticatedDatasetsIndexRouteImport } from './routes/_authenticated/datasets.index'
import { Route as AuthenticatedRunsIdRouteImport } from './routes/_authenticated/runs.$id'
import { Route as AuthenticatedDatasetsIdRouteImport } from './routes/_authenticated/datasets.$id'
import { Route as AuthenticatedDatasetsIdModelRouteImport } from './routes/_authenticated/datasets.$id.model'
import { Route as AuthenticatedDatasetsIdExploreRouteImport } from './routes/_authenticated/datasets.$id.explore'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunsIndexRoute = AuthenticatedRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDatasetsIndexRoute =
  AuthenticatedDatasetsIndexRouteImport.update({
    id: '/datasets/',
    path: '/datasets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRunsIdRoute = AuthenticatedRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDatasetsIdRoute = AuthenticatedDatasetsIdRouteImport.update({
  id: '/datasets/$id',
  path: '/datasets/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDatasetsIdModelRoute =
  AuthenticatedDatasetsIdModelRouteImport.update({
    id: '/model',
    path: '/model',
    getParentRoute: () => AuthenticatedDatasetsIdRoute,
  } as any)
const AuthenticatedDatasetsIdExploreRoute =
  AuthenticatedDatasetsIdExploreRouteImport.update({
    id: '/explore',
    path: '/explore',
    getParentRoute: () => AuthenticatedDatasetsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/datasets/$id': typeof AuthenticatedDatasetsIdRouteWithChildren
  '/runs/$id': typeof AuthenticatedRunsIdRoute
  '/datasets/': typeof AuthenticatedDatasetsIndexRoute
  '/runs/': typeof AuthenticatedRunsIndexRoute
  '/datasets/$id/explore': typeof AuthenticatedDatasetsIdExploreRoute
  '/datasets/$id/model': typeof AuthenticatedDatasetsIdModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/datasets/$id': typeof AuthenticatedDatasetsIdRouteWithChildren
  '/runs/$id': typeof AuthenticatedRunsIdRoute
  '/datasets': typeof AuthenticatedDatasetsIndexRoute
  '/runs': typeof AuthenticatedRunsIndexRoute
  '/datasets/$id/explore': typeof AuthenticatedDatasetsIdExploreRoute
  '/datasets/$id/model': typeof AuthenticatedDatasetsIdModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/datasets/$id': typeof AuthenticatedDatasetsIdRouteWithChildren
  '/_authenticated/runs/$id': typeof AuthenticatedRunsIdRoute
  '/_authenticated/datasets/': typeof AuthenticatedDatasetsIndexRoute
  '/_authenticated/runs/': typeof AuthenticatedRunsIndexRoute
  '/_authenticated/datasets/$id/explore': typeof AuthenticatedDatasetsIdExploreRoute
  '/_authenticated/datasets/$id/model': typeof AuthenticatedDatasetsIdModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/explore'
    | '/upload'
    | '/datasets/$id'
    | '/runs/$id'
    | '/datasets/'
    | '/runs/'
    | '/datasets/$id/explore'
    | '/datasets/$id/model'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/explore'
    | '/upload'
    | '/datasets/$id'
    | '/runs/$id'
    | '/datasets'
    | '/runs'
    | '/datasets/$id/explore'
    | '/datasets/$id/model'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/explore'
    | '/_authenticated/upload'
    | '/_authenticated/datasets/$id'
    | '/_authenticated/runs/$id'
    | '/_authenticated/datasets/'
    | '/_authenticated/runs/'
    | '/_authenticated/datasets/$id/explore'
    | '/_authenticated/datasets/$id/model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs/': {
      id: '/_authenticated/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthenticatedRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/datasets/': {
      id: '/_authenticated/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof AuthenticatedDatasetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs/$id': {
      id: '/_authenticated/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof AuthenticatedRunsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/datasets/$id': {
      id: '/_authenticated/datasets/$id'
      path: '/datasets/$id'
      fullPath: '/datasets/$id'
      preLoaderRoute: typeof AuthenticatedDatasetsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/datasets/$id/model': {
      id: '/_authenticated/datasets/$id/model'
      path: '/model'
      fullPath: '/datasets/$id/model'
      preLoaderRoute: typeof AuthenticatedDatasetsIdModelRouteImport
      parentRoute: typeof AuthenticatedDatasetsIdRoute
    }
    '/_authenticated/datasets/$id/explore': {
      id: '/_authenticated/datasets/$id/explore'
      path: '/explore'
      fullPath: '/datasets/$id/explore'
      preLoaderRoute: typeof AuthenticatedDatasetsIdExploreRouteImport
      parentRoute: typeof AuthenticatedDatasetsIdRoute
    }
  }
}

interface AuthenticatedDatasetsIdRouteChildren {
  AuthenticatedDatasetsIdExploreRoute: typeof AuthenticatedDatasetsIdExploreRoute
  AuthenticatedDatasetsIdModelRoute: typeof AuthenticatedDatasetsIdModelRoute
}

const AuthenticatedDatasetsIdRouteChildren: AuthenticatedDatasetsIdRouteChildren =
  {
    AuthenticatedDatasetsIdExploreRoute: AuthenticatedDatasetsIdExploreRoute,
    AuthenticatedDatasetsIdModelRoute: AuthenticatedDatasetsIdModelRoute,
  }

const AuthenticatedDatasetsIdRouteWithChildren =
  AuthenticatedDatasetsIdRoute._addFileChildren(
    AuthenticatedDatasetsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedDatasetsIdRoute: typeof AuthenticatedDatasetsIdRouteWithChildren
  AuthenticatedRunsIdRoute: typeof AuthenticatedRunsIdRoute
  AuthenticatedDatasetsIndexRoute: typeof AuthenticatedDatasetsIndexRoute
  AuthenticatedRunsIndexRoute: typeof AuthenticatedRunsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedDatasetsIdRoute: AuthenticatedDatasetsIdRouteWithChildren,
  AuthenticatedRunsIdRoute: AuthenticatedRunsIdRoute,
  AuthenticatedDatasetsIndexRoute: AuthenticatedDatasetsIndexRoute,
  AuthenticatedRunsIndexRoute: AuthenticatedRunsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
