/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedRunsIndexRouteImport } from './routes/_authenticated/runs.index'
import { Route as AuthenticatedResultsIndexRouteImport } from './routes/_authenticated/results.index'
import { Route as AuthenticatedDatasetsIndexRouteImport } from './routes/_authenticated/datasets.index'
import { Route as ShareRunsIdRouteImport } from './routes/share.runs.$id'
import { Route as AuthenticatedRunsIdRouteImport } from './routes/_authenticated/runs.$id'
import { Route as AuthenticatedResultsRoiRouteImport } from './routes/_authenticated/results.roi'
import { Route as AuthenticatedResultsResponseRouteImport } from './routes/_authenticated/results.response'
import { Route as AuthenticatedResultsOptimizerRouteImport } from './routes/_authenticated/results.optimizer'
import { Route as AuthenticatedResultsDecompRouteImport } from './routes/_authenticated/results.decomp'
import { Route as AuthenticatedDatasetsIdRouteImport } from './routes/_authenticated/datasets.$id'
import { Route as AuthenticatedDatasetsIdIndexRouteImport } from './routes/_authenticated/datasets.$id.index'
import { Route as AuthenticatedDatasetsIdModelRouteImport } from './routes/_authenticated/datasets.$id.model'
import { Route as AuthenticatedDatasetsIdExploreRouteImport } from './routes/_authenticated/datasets.$id.explore'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunsIndexRoute = AuthenticatedRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultsIndexRoute =
  AuthenticatedResultsIndexRouteImport.update({
    id: '/results/',
    path: '/results/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDatasetsIndexRoute =
  AuthenticatedDatasetsIndexRouteImport.update({
    id: '/datasets/',
    path: '/datasets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ShareRunsIdRoute = ShareRunsIdRouteImport.update({
  id: '/share/runs/$id',
  path: '/share/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRunsIdRoute = AuthenticatedRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultsRoiRoute = AuthenticatedResultsRoiRouteImport.update({
  id: '/results/roi',
  path: '/results/roi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultsResponseRoute =
  AuthenticatedResultsResponseRouteImport.update({
    id: '/results/response',
    path: '/results/response',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResultsOptimizerRoute =
  AuthenticatedResultsOptimizerRouteImport.update({
    id: '/results/optimizer',
    path: '/results/optimizer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResultsDecompRoute =
  AuthenticatedResultsDecompRouteImport.update({
    id: '/results/decomp',
    path: '/results/decomp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDatasetsIdRoute = AuthenticatedDatasetsIdRouteImport.update({
  id: '/datasets/$id',
  path: '/datasets/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDatasetsIdIndexRoute =
  AuthenticatedDatasetsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDatasetsIdRoute,
  } as any)
const AuthenticatedDatasetsIdModelRoute =
  AuthenticatedDatasetsIdModelRouteImport.update({
    id: '/model',
    path: '/model',
    getParentRoute: () => AuthenticatedDatasetsIdRoute,
  } as any)
const AuthenticatedDatasetsIdExploreRoute =
  AuthenticatedDatasetsIdExploreRouteImport.update({
    id: '/explore',
    path: '/explore',
    getParentRoute: () => AuthenticatedDatasetsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/datasets/$id': typeof AuthenticatedDatasetsIdRouteWithChildren
  '/results/decomp': typeof AuthenticatedResultsDecompRoute
  '/results/optimizer': typeof AuthenticatedResultsOptimizerRoute
  '/results/response': typeof AuthenticatedResultsResponseRoute
  '/results/roi': typeof AuthenticatedResultsRoiRoute
  '/runs/$id': typeof AuthenticatedRunsIdRoute
  '/share/runs/$id': typeof ShareRunsIdRoute
  '/datasets/': typeof AuthenticatedDatasetsIndexRoute
  '/results/': typeof AuthenticatedResultsIndexRoute
  '/runs/': typeof AuthenticatedRunsIndexRoute
  '/datasets/$id/explore': typeof AuthenticatedDatasetsIdExploreRoute
  '/datasets/$id/model': typeof AuthenticatedDatasetsIdModelRoute
  '/datasets/$id/': typeof AuthenticatedDatasetsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/results/decomp': typeof AuthenticatedResultsDecompRoute
  '/results/optimizer': typeof AuthenticatedResultsOptimizerRoute
  '/results/response': typeof AuthenticatedResultsResponseRoute
  '/results/roi': typeof AuthenticatedResultsRoiRoute
  '/runs/$id': typeof AuthenticatedRunsIdRoute
  '/share/runs/$id': typeof ShareRunsIdRoute
  '/datasets': typeof AuthenticatedDatasetsIndexRoute
  '/results': typeof AuthenticatedResultsIndexRoute
  '/runs': typeof AuthenticatedRunsIndexRoute
  '/datasets/$id/explore': typeof AuthenticatedDatasetsIdExploreRoute
  '/datasets/$id/model': typeof AuthenticatedDatasetsIdModelRoute
  '/datasets/$id': typeof AuthenticatedDatasetsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/datasets/$id': typeof AuthenticatedDatasetsIdRouteWithChildren
  '/_authenticated/results/decomp': typeof AuthenticatedResultsDecompRoute
  '/_authenticated/results/optimizer': typeof AuthenticatedResultsOptimizerRoute
  '/_authenticated/results/response': typeof AuthenticatedResultsResponseRoute
  '/_authenticated/results/roi': typeof AuthenticatedResultsRoiRoute
  '/_authenticated/runs/$id': typeof AuthenticatedRunsIdRoute
  '/share/runs/$id': typeof ShareRunsIdRoute
  '/_authenticated/datasets/': typeof AuthenticatedDatasetsIndexRoute
  '/_authenticated/results/': typeof AuthenticatedResultsIndexRoute
  '/_authenticated/runs/': typeof AuthenticatedRunsIndexRoute
  '/_authenticated/datasets/$id/explore': typeof AuthenticatedDatasetsIdExploreRoute
  '/_authenticated/datasets/$id/model': typeof AuthenticatedDatasetsIdModelRoute
  '/_authenticated/datasets/$id/': typeof AuthenticatedDatasetsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/forgot-password'
    | '/login'
    | '/methodology'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/termos'
    | '/admin'
    | '/compare'
    | '/explore'
    | '/upload'
    | '/datasets/$id'
    | '/results/decomp'
    | '/results/optimizer'
    | '/results/response'
    | '/results/roi'
    | '/runs/$id'
    | '/share/runs/$id'
    | '/datasets/'
    | '/results/'
    | '/runs/'
    | '/datasets/$id/explore'
    | '/datasets/$id/model'
    | '/datasets/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/forgot-password'
    | '/login'
    | '/methodology'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/termos'
    | '/admin'
    | '/compare'
    | '/explore'
    | '/upload'
    | '/results/decomp'
    | '/results/optimizer'
    | '/results/response'
    | '/results/roi'
    | '/runs/$id'
    | '/share/runs/$id'
    | '/datasets'
    | '/results'
    | '/runs'
    | '/datasets/$id/explore'
    | '/datasets/$id/model'
    | '/datasets/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/demo'
    | '/forgot-password'
    | '/login'
    | '/methodology'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/compare'
    | '/_authenticated/explore'
    | '/_authenticated/upload'
    | '/_authenticated/datasets/$id'
    | '/_authenticated/results/decomp'
    | '/_authenticated/results/optimizer'
    | '/_authenticated/results/response'
    | '/_authenticated/results/roi'
    | '/_authenticated/runs/$id'
    | '/share/runs/$id'
    | '/_authenticated/datasets/'
    | '/_authenticated/results/'
    | '/_authenticated/runs/'
    | '/_authenticated/datasets/$id/explore'
    | '/_authenticated/datasets/$id/model'
    | '/_authenticated/datasets/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ShareRunsIdRoute: typeof ShareRunsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs/': {
      id: '/_authenticated/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthenticatedRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results/': {
      id: '/_authenticated/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof AuthenticatedResultsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/datasets/': {
      id: '/_authenticated/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof AuthenticatedDatasetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/share/runs/$id': {
      id: '/share/runs/$id'
      path: '/share/runs/$id'
      fullPath: '/share/runs/$id'
      preLoaderRoute: typeof ShareRunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/runs/$id': {
      id: '/_authenticated/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof AuthenticatedRunsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results/roi': {
      id: '/_authenticated/results/roi'
      path: '/results/roi'
      fullPath: '/results/roi'
      preLoaderRoute: typeof AuthenticatedResultsRoiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results/response': {
      id: '/_authenticated/results/response'
      path: '/results/response'
      fullPath: '/results/response'
      preLoaderRoute: typeof AuthenticatedResultsResponseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results/optimizer': {
      id: '/_authenticated/results/optimizer'
      path: '/results/optimizer'
      fullPath: '/results/optimizer'
      preLoaderRoute: typeof AuthenticatedResultsOptimizerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results/decomp': {
      id: '/_authenticated/results/decomp'
      path: '/results/decomp'
      fullPath: '/results/decomp'
      preLoaderRoute: typeof AuthenticatedResultsDecompRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/datasets/$id': {
      id: '/_authenticated/datasets/$id'
      path: '/datasets/$id'
      fullPath: '/datasets/$id'
      preLoaderRoute: typeof AuthenticatedDatasetsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/datasets/$id/': {
      id: '/_authenticated/datasets/$id/'
      path: '/'
      fullPath: '/datasets/$id/'
      preLoaderRoute: typeof AuthenticatedDatasetsIdIndexRouteImport
      parentRoute: typeof AuthenticatedDatasetsIdRoute
    }
    '/_authenticated/datasets/$id/model': {
      id: '/_authenticated/datasets/$id/model'
      path: '/model'
      fullPath: '/datasets/$id/model'
      preLoaderRoute: typeof AuthenticatedDatasetsIdModelRouteImport
      parentRoute: typeof AuthenticatedDatasetsIdRoute
    }
    '/_authenticated/datasets/$id/explore': {
      id: '/_authenticated/datasets/$id/explore'
      path: '/explore'
      fullPath: '/datasets/$id/explore'
      preLoaderRoute: typeof AuthenticatedDatasetsIdExploreRouteImport
      parentRoute: typeof AuthenticatedDatasetsIdRoute
    }
  }
}

interface AuthenticatedDatasetsIdRouteChildren {
  AuthenticatedDatasetsIdExploreRoute: typeof AuthenticatedDatasetsIdExploreRoute
  AuthenticatedDatasetsIdModelRoute: typeof AuthenticatedDatasetsIdModelRoute
  AuthenticatedDatasetsIdIndexRoute: typeof AuthenticatedDatasetsIdIndexRoute
}

const AuthenticatedDatasetsIdRouteChildren: AuthenticatedDatasetsIdRouteChildren =
  {
    AuthenticatedDatasetsIdExploreRoute: AuthenticatedDatasetsIdExploreRoute,
    AuthenticatedDatasetsIdModelRoute: AuthenticatedDatasetsIdModelRoute,
    AuthenticatedDatasetsIdIndexRoute: AuthenticatedDatasetsIdIndexRoute,
  }

const AuthenticatedDatasetsIdRouteWithChildren =
  AuthenticatedDatasetsIdRoute._addFileChildren(
    AuthenticatedDatasetsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedDatasetsIdRoute: typeof AuthenticatedDatasetsIdRouteWithChildren
  AuthenticatedResultsDecompRoute: typeof AuthenticatedResultsDecompRoute
  AuthenticatedResultsOptimizerRoute: typeof AuthenticatedResultsOptimizerRoute
  AuthenticatedResultsResponseRoute: typeof AuthenticatedResultsResponseRoute
  AuthenticatedResultsRoiRoute: typeof AuthenticatedResultsRoiRoute
  AuthenticatedRunsIdRoute: typeof AuthenticatedRunsIdRoute
  AuthenticatedDatasetsIndexRoute: typeof AuthenticatedDatasetsIndexRoute
  AuthenticatedResultsIndexRoute: typeof AuthenticatedResultsIndexRoute
  AuthenticatedRunsIndexRoute: typeof AuthenticatedRunsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedDatasetsIdRoute: AuthenticatedDatasetsIdRouteWithChildren,
  AuthenticatedResultsDecompRoute: AuthenticatedResultsDecompRoute,
  AuthenticatedResultsOptimizerRoute: AuthenticatedResultsOptimizerRoute,
  AuthenticatedResultsResponseRoute: AuthenticatedResultsResponseRoute,
  AuthenticatedResultsRoiRoute: AuthenticatedResultsRoiRoute,
  AuthenticatedRunsIdRoute: AuthenticatedRunsIdRoute,
  AuthenticatedDatasetsIndexRoute: AuthenticatedDatasetsIndexRoute,
  AuthenticatedResultsIndexRoute: AuthenticatedResultsIndexRoute,
  AuthenticatedRunsIndexRoute: AuthenticatedRunsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ShareRunsIdRoute: ShareRunsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
